-- Luaモジュールキャッシュ機能 起動を少し高速化
pcall(function()
	vim.loader.enable()
end)

require("colors")
require("options")
require("keymaps")
require("plugins")
require("lsp")
require("format")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.hlchunk")
require("plugins.toggleterm")
require("plugins.barbar")
require("plugins.git")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.treesitter")
