# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

git:
  pagers:
    - pager: delta --light --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

customCommands:
  - key: "B"
    command: "git czg"
    context: files
    output: terminal

gui:
  language: "ja"
