# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# BACKGROUND
background {
    color = 0x1e1e2e   # ダークグレー
}

# INPUT FIELD
input-field {
    monitor = eDP-1
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">🔒 Enter Pass</span></i>
    hide_input = false

    # ↓ 中央配置に変更
    position = 0, 0
    halign = center
    valign = center
}

